

let vidCategoryArray = [
    {cat: 'All', isActive: true},
    {cat: 'Music', isActive: false},
    {cat: 'Animals', isActive: false},
    {cat: 'Sports', isActive: false},
    {cat: 'Travel', isActive: false},
    {cat: 'Gaming', isActive: false},
    {cat: 'Blogs', isActive: false},
    {cat: 'Comedy', isActive: false},
    {cat: 'Entertainment', isActive: false},
    {cat: 'Movie', isActive: false}
]



let videoCollection = [
    {
        id: 0,
        authorID: 0,
        authorProfile: 'https://yt3.ggpht.com/rPTMAygaSNkMnSRNRscSk8LYA_d_lUSUbVnswtDjYpzz_Xf7WXXvCL4G7eDmgclQqcIJRwwBAw4=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'Beluga',
        subscribed: false,
        recommended: true,
        subscribers: '9.51M',
        videoThumbnail: 'https://i.ytimg.com/vi/69Hitt9Dw4Y/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBq_g5bqdL2kclq7aoq1pstuoZFSA',
        videoURL: 'https://www.youtube.com/embed/69Hitt9Dw4Y',
        videoTitle:'When a hacker finds your password',
        videoDuration:'3:09',
        videoAge:'1 year ago',
        views:'35M',
        cat: 'Comedy',
        playlist: 1,
        like: false 
    },{
        id: 1,
        authorID: 0,
        authorProfile: 'https://yt3.ggpht.com/rPTMAygaSNkMnSRNRscSk8LYA_d_lUSUbVnswtDjYpzz_Xf7WXXvCL4G7eDmgclQqcIJRwwBAw4=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'Beluga',
        subscribed: false,
        recommended: true,
        subscribers: '9.51M',
        videoThumbnail: 'https://i.ytimg.com/vi/2s5V3oW2iUs/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC-32goepcUok9RS4AzbmTJT7TTuA',
        videoURL: 'https://www.youtube.com/embed/2s5V3oW2iUs',
        videoTitle:'When your phone is at 1%',
        videoDuration:'2:03',
        videoAge:'1 year ago',
        views:'5M',
        cat: 'Comedy',
        playlist: 1,
        like: false 
    },{
        id: 2,
        authorID: 0,
        authorProfile: 'https://yt3.ggpht.com/rPTMAygaSNkMnSRNRscSk8LYA_d_lUSUbVnswtDjYpzz_Xf7WXXvCL4G7eDmgclQqcIJRwwBAw4=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'Beluga',
        subscribed: false,
        recommended: true,
        subscribers: '9.51M',
        videoThumbnail: 'https://i.ytimg.com/vi/LgQoqCjIGak/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCvjnxBVhvxdg9DYXbOROamOAj2Ew',
        videoURL: 'https://www.youtube.com/embed/LgQoqCjIGak',
        videoTitle:'When you cheat in school',
        videoDuration:'3:21',
        videoAge:'1 year ago',
        views:'9M',
        cat: 'Comedy',
        playlist: 1,
        like: false 
    },{
        id: 3,
        authorID: 0,
        authorProfile: 'https://yt3.ggpht.com/rPTMAygaSNkMnSRNRscSk8LYA_d_lUSUbVnswtDjYpzz_Xf7WXXvCL4G7eDmgclQqcIJRwwBAw4=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'Beluga',
        subscribed: false,
        recommended: true,
        subscribers: '9.51M',
        videoThumbnail: 'https://i.ytimg.com/vi/e5w46zCY-Us/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAUsfCHS3j5VKVUFOAivTHb0bEO6g',
        videoURL: 'https://www.youtube.com/embed/e5w46zCY-Us',
        videoTitle:'When your phone charges overnight',
        videoDuration:'2:51',
        videoAge:'1 year ago',
        views:'2M',
        cat: 'Comedy',
        playlist: 1,
        like: false 
    },{
        id: 4,
        authorID: 0,
        authorProfile: 'https://yt3.ggpht.com/rPTMAygaSNkMnSRNRscSk8LYA_d_lUSUbVnswtDjYpzz_Xf7WXXvCL4G7eDmgclQqcIJRwwBAw4=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'Beluga',
        subscribed: false,
        recommended: true,
        subscribers: '9.51M',
        videoThumbnail: 'https://i.ytimg.com/vi/_SZxzwQmT8A/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBX8j-GM4VxBuMCJIRwZBs1WivUKg',
        videoURL: 'https://www.youtube.com/embed/_SZxzwQmT8A',
        videoTitle:'Im from the future',
        videoDuration:'3:21',
        videoAge:'8 days ago',
        views:'665K',
        cat: 'Comedy',
        playlist: 1,
        like: false 
    },{
        id: 5,
        authorID: 1,
        authorProfile: 'https://yt3.googleusercontent.com/ytc/AL5GRJVnwud9mJ9seCrx-CXI-n4xHzUEmSv7F3FWy7UzlA=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'GameClips',
        subscribed: false,
        recommended: true,
        subscribers: '3.88M',
        videoThumbnail: 'https://i.ytimg.com/vi/uRENpIXy4yk/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBDhsJQhsdiYE8KcQZ0b3FMcuNpUg',
        videoURL: 'https://www.youtube.com/embed/pRzIS4921pU',
        videoTitle:'Halo Spartan',
        videoDuration:'5:34',
        videoAge:'2 days ago',
        views:'4.8K',
        cat: 'Movie',
        playlist: 1,
        like: false 
    },{
        id: 6,
        authorID: 1,
        authorProfile: 'https://yt3.googleusercontent.com/ytc/AL5GRJVnwud9mJ9seCrx-CXI-n4xHzUEmSv7F3FWy7UzlA=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'GameClips',
        subscribed: false,
        recommended: true,
        subscribers: '3.88M',
        videoThumbnail: 'https://i.ytimg.com/vi/JJ7Pecu2ZFc/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLD3mbKxGv6bPrb28LDzGyjoqA7Q0w',
        videoURL: 'https://www.youtube.com/embed/p7cmoSVOJX8',
        videoTitle:'Diablo 4 Lilith vs Inarius',
        videoDuration:'10:23',
        videoAge:'2 days ago',
        views:'14K',
        cat: 'Movie',
        playlist: 1,
        like: false 
    },{
        id: 7,
        authorID: 1,
        authorProfile: 'https://yt3.googleusercontent.com/ytc/AL5GRJVnwud9mJ9seCrx-CXI-n4xHzUEmSv7F3FWy7UzlA=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'GameClips',
        subscribed: false,
        recommended: true,
        subscribers: '3.88M',
        videoThumbnail: 'https://i.ytimg.com/vi/nsZObkD1dog/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAOCD0ZRrPNP-bIosmMnYQCZhWvKg',
        videoURL: 'https://www.youtube.com/embed/nsZObkD1dog',
        videoTitle:'The Walking Dead',
        videoDuration:'12:18',
        videoAge:'2 years ago',
        views:'67M',
        cat: 'Movie',
        playlist: 1,
        like: false 
    },{
        id: 8,
        authorID: 1,
        authorProfile: 'https://yt3.googleusercontent.com/ytc/AL5GRJVnwud9mJ9seCrx-CXI-n4xHzUEmSv7F3FWy7UzlA=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'GameClips',
        subscribed: false,
        recommended: true,
        subscribers: '3.88M',
        videoThumbnail: 'https://i.ytimg.com/vi/daaS4So3kYc/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA7F4B6RUwqRP2DcGkfMhw00v8TtA',
        videoURL: 'https://www.youtube.com/embed/Ek-5JMwBuIw',
        videoTitle:'The amazing spiderman',
        videoDuration:'21:36',
        videoAge:'2 years ago',
        views:'18M',
        cat: 'Movie',
        playlist: 1,
        like: false 
    },{
        id: 9,
        authorID: 1,
        authorProfile: 'https://yt3.googleusercontent.com/ytc/AL5GRJVnwud9mJ9seCrx-CXI-n4xHzUEmSv7F3FWy7UzlA=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'GameClips',
        subscribed: false,
        recommended: true,
        subscribers: '3.88M',
        videoThumbnail: 'https://i.ytimg.com/vi/jRqz14Vgs08/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBvpCyvft4vxrPkoG6pwkNgF6w-Ow',
        videoURL: 'https://www.youtube.com/embed/Io5iGOazyaE',
        videoTitle:'The Witcher Full movie',
        videoDuration:'18:29',
        videoAge:'2 years ago',
        views:'15M',
        cat: 'Movie',
        playlist: 1,
        like: false 
    },{
        id: 10,
        authorID: 2,
        authorProfile: 'https://yt3.ggpht.com/IFAdSHe3eG1PB0hhxuDucjwhLgGKYaapvBSFnWWYvzCcNVz9E95PFfgwtG0U3nwDsyfejsq_sdc=s68-c-k-c0x00ffffff-no-rj',
        authorName: 'Kankusubs',
        subscribed: false,
        recommended: true,
        subscribers: '121K',
        videoThumbnail: 'https://i.ytimg.com/vi/RIddpBthe5s/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBKhiW8ce1xHlV99p7W6xVARX2W7g',
        videoURL:'https://www.youtube.com/embed/RIddpBthe5s',
        videoTitle: 'amanojaku',
        videoDuration:'4:24',
        videoAge:'4 years ago',
        views:'15M',
        cat: 'Music',
        playlist: 1,
        like: false 
    },{
        id: 11,
        authorID: 3,
        authorProfile: 'https://yt3.ggpht.com/7RiTz9Fp2lcD5dgKYUlaB2bY64gM1PvO1OUjbtcbyzrOdgqc_4jtfVh4vUjxyZ9E7F97ouBa=s176-c-k-c0x00ffffff-no-rj-mo',
        authorName: 'Arwicial Vibe',
        subscribed: false,
        recommended: true,
        subscribers: '340K',
        videoThumbnail: 'https://i.ytimg.com/vi/fWpbsFA_Ouk/hq720.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4Af4JgALQBYoCDAgAEAEYRSBCKGUwDw==&rs=AOn4CLCVp2WTEjQAyYildx1B-UiCCCIirg',
        videoURL: 'https://www.youtube.com/embed/fWpbsFA_Ouk',
        videoTitle:'kokoronashi',
        videoDuration:'4:39',
        videoAge:'3 years ago',
        views:'25M',
        cat: 'Music',
        playlist: 1,
        like: false 
    },{
        id: 12,
        authorID: 4,
        authorProfile: 'https://yt3.ggpht.com/J44iSHmkbPs88aAWqevGNMmv1zym7HmBjj6mzdynOJYGFWjW5UfkqKAcPhBnKAOKQN2IN23lmg=s68-c-k-c0x00ffffff-no-rj',
        authorName: 'Smart Pizza',
        subscribed: false,
        recommended: true,
        subscribers: '160K',
        videoThumbnail: 'https://i.ytimg.com/vi/TYgQQI3Fazc/hq720.jpg?sqp=-…AFwAcABBg==&rs=AOn4CLB21Azu5bUqAbRf-bIekkGMQZaWdw',
        videoURL: 'https://www.youtube.com/embed/TYgQQI3Fazc',
        videoTitle:'100 crazy animal fights',
        videoDuration:'57:10',
        videoAge:'4 months ago',
        views:'2.6M',
        cat: 'Animals',
        playlist: 1,
        like: false 
    }
]




let allArray = [{vidCategoryArray,videoCollection}]

export default allArray